#!/bin/sh

# copy 6lbr dir to the system file
if [ ! -d /etc/6lbr ]; then
    install -d -m755 /etc/6lbr
    install -m755  -r snap/6lbr/current/etc/6lbr /etc

fi
# copy 6lbr init file to the system file
if [ ! -d /etc/init.d/6lbr ]; then
    install -r -m755 snap/6lbr/current/etc/init.d/* /etc/init.d
    update-rc.d 6lbr defaults
fi

if [ ! -d /usr/bin/6lbr ]; then
    install -d -m755 /usr/bin/6lbr
    install -m755 -r snap/6lbr/current/usr/bin/* /usr/bin

fi

if [ ! -d /usr/lib/6lbr ]; then
    install -d -m755 /usr/lib/6lb
    install -m755  -r snap/6lbr/current/usr/lib/6lbr /usr/lib

fi
